#!/bin/bash
# STUN/TURN Server Installation Script for Ubuntu 22.04/24.04
# Run as root: sudo bash install.sh

set -e

echo "=========================================="
echo "  STUN/TURN Server Installation"
echo "=========================================="

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo "Please run as root: sudo bash install.sh"
    exit 1
fi

# Get server's public IP
PUBLIC_IP=$(curl -s ifconfig.me || curl -s icanhazip.com)
echo "Detected public IP: $PUBLIC_IP"

# Update system
echo "[1/6] Updating system..."
apt-get update -qq
apt-get upgrade -y -qq

# Install coturn
echo "[2/6] Installing Coturn..."
apt-get install -y coturn

# Enable coturn service
echo "[3/6] Enabling Coturn service..."
sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/' /etc/default/coturn

# Backup original config
cp /etc/turnserver.conf /etc/turnserver.conf.original

# Create new configuration
echo "[4/6] Creating configuration..."
cat > /etc/turnserver.conf << EOF
# STUN Server Configuration
# Generated by install.sh on $(date)

# Listening ports
listening-port=3478
alt-listening-port=3479

# Server IP
listening-ip=$PUBLIC_IP
external-ip=$PUBLIC_IP

# Realm
realm=$PUBLIC_IP

# STUN-only mode (no TURN relay)
stun-only

# No authentication (public STUN)
no-auth
fingerprint

# Disable TLS
no-tls
no-dtls

# Logging
verbose
syslog

# Process
proc-user=turnserver
proc-group=turnserver
min-port=49152
max-port=65535
EOF

# Configure firewall
echo "[5/6] Configuring firewall..."
if command -v ufw &> /dev/null; then
    ufw allow 3478/udp
    ufw allow 3478/tcp
    ufw allow 3479/udp
    ufw allow 3479/tcp
    echo "UFW rules added"
fi

# Also add iptables rules
iptables -A INPUT -p udp --dport 3478 -j ACCEPT 2>/dev/null || true
iptables -A INPUT -p udp --dport 3479 -j ACCEPT 2>/dev/null || true
iptables -A INPUT -p tcp --dport 3478 -j ACCEPT 2>/dev/null || true
iptables -A INPUT -p tcp --dport 3479 -j ACCEPT 2>/dev/null || true

# Save iptables rules
if command -v netfilter-persistent &> /dev/null; then
    netfilter-persistent save
fi

# Restart coturn
echo "[6/6] Starting Coturn..."
systemctl restart coturn
systemctl enable coturn

# Verify
sleep 2
if systemctl is-active --quiet coturn; then
    echo ""
    echo "=========================================="
    echo "  ✅ STUN Server Installed Successfully!"
    echo "=========================================="
    echo ""
    echo "Server Address: $PUBLIC_IP:3478"
    echo ""
    echo "Test with:"
    echo "  stun $PUBLIC_IP"
    echo ""
    echo "Use in WebRTC:"
    echo "  { urls: 'stun:$PUBLIC_IP:3478' }"
    echo ""
else
    echo "❌ Failed to start Coturn. Check logs:"
    echo "  journalctl -u coturn -n 50"
    exit 1
fi
